// Build the production-ready package: everything needed to take a project to
// the physical world — code for the board, STL for the da Vinci mini maker,
// SVG for the Silhouette Cameo label cutter, and a summary (cost, Amazon
// links, thermal breaking point). The main process writes it to the library.
import { PART_BY_ID } from '../data/parts.js';
import { numberedNodeNames } from './labels.js';
import { resolveMaterial } from './lifesim.js';
import { circuitToSvg } from './circuitSvg.js';
import { exportSceneToStl } from './exportScene.js';
import { amazonUrl } from './links.js';

const PI_SETUP = `# Raspberry Pi 5 — setup
This package includes the Python program (main .py file) for your Raspberry Pi 5.

The Raspberry Pi OS image is several GB, so it is NOT bundled here.
Get it (free, official):

1. Download **Raspberry Pi Imager**: https://www.raspberrypi.com/software/
2. Flash **Raspberry Pi OS (64-bit)** onto a microSD card (16 GB+).
3. Boot the Pi, copy the .py file over (USB stick or \`scp\`).
4. Install the GPIO library and run it:

   sudo apt update && sudo apt install -y python3-gpiozero
   python3 your_program.py
`;

function summaryMd({ name, nodes, wires, meshes, bomRows, bomTotal, hasPi, hasArduino }) {
  const lines = [];
  lines.push(`# ${name} — production summary`);
  lines.push(`Generated by Forge3D on ${new Date().toLocaleString()}`);
  lines.push('');
  lines.push(`Circuit: ${nodes.length} parts · ${wires.length} wires · 3D scene: ${meshes.length} objects`);
  lines.push('');

  // thermal breaking point: the first element to fail, from assigned materials
  const rated = meshes
    .map((m) => ({ label: m.label || m.kind, mat: resolveMaterial(m) }))
    .filter((x) => x.mat && Number.isFinite(x.mat.maxTempC));
  if (rated.length) {
    const weakest = rated.reduce((a, b) => (b.mat.maxTempC < a.mat.maxTempC ? b : a));
    lines.push('## Breaking point (thermal)');
    lines.push(`**${weakest.mat.maxTempC}°C** — first element to fail: **${weakest.label}** (${weakest.mat.name}).`);
    lines.push('Keep the assembly below this temperature.');
    lines.push('');
  }

  lines.push('## Bill of materials');
  lines.push('| Part | Qty | Unit | Total | Buy |');
  lines.push('|---|---|---|---|---|');
  for (const r of bomRows) {
    lines.push(`| ${r.name} | ${r.qty} | $${r.unit.toFixed(2)} | $${r.total.toFixed(2)} | [Amazon](${amazonUrl(r.name)}) |`);
  }
  lines.push(`| **TOTAL** |  |  | **$${bomTotal.toFixed(2)}** |  |`);
  lines.push('');
  lines.push('Unit prices are typical estimates — the Amazon links show live pricing.');
  lines.push('');

  lines.push('## Files in this package');
  lines.push('- `*.svg` → **Silhouette Cameo**: cut the label/sticker traces, transfer to the board, etch with ferric acid.');
  lines.push('- `*.stl` → **da Vinci mini maker** (open in XYZware and print).');
  if (hasArduino) lines.push('- `*.ino` → open in Arduino IDE, select the board, upload.');
  if (hasPi) lines.push('- `*.py` → copy to the Raspberry Pi 5 (see RASPBERRY_PI_SETUP.md).');
  lines.push('- `*.f3d` → re-open in Forge3D to keep editing.');
  return lines.join('\n');
}

// Returns [{ name, content, encoding? }] ready for production:export.
export async function buildProductionFiles({ name, serialize, nodes, wires, meshes, codeByNode, bom, quality }) {
  const files = [];
  const names = numberedNodeNames(nodes);
  const safe = (s) => String(s).replace(/[^\w.\-]+/g, '_').toLowerCase();

  // 1) editable source
  files.push({ name: `${safe(name)}.f3d`, content: serialize() });

  // 2) board code (.ino for Arduino-likes, .py for the Pi 5)
  let hasPi = false;
  let hasArduino = false;
  for (const n of nodes) {
    const part = PART_BY_ID[n.partId];
    if (part?.category !== 'Microcontrollers') continue;
    const code = codeByNode[n.id];
    if (!code || !code.trim()) continue;
    if (n.partId === 'rpi5') {
      hasPi = true;
      files.push({ name: `${safe(names[n.id] || part.name)}.py`, content: code });
    } else {
      hasArduino = true;
      files.push({ name: `${safe(names[n.id] || part.name)}.ino`, content: code });
    }
  }
  if (hasPi) files.push({ name: 'RASPBERRY_PI_SETUP.md', content: PI_SETUP });

  // 3) 3D model for the da Vinci mini maker
  if (meshes.length) {
    files.push({ name: `${safe(name)}.stl`, content: await exportSceneToStl(meshes, quality), encoding: 'base64' });
  }

  // 4) cutter SVG for the Silhouette Cameo
  if (nodes.length) {
    files.push({ name: `${safe(name)}_cutter.svg`, content: circuitToSvg(nodes, wires) });
  }

  // 5) summary: cost, links, breaking point, instructions
  const { rows, total } = bom;
  files.push({ name: 'SUMMARY.md', content: summaryMd({ name, nodes, wires, meshes, bomRows: rows, bomTotal: total, hasPi, hasArduino }) });

  return files;
}
